// Provas exclusivas 2E: Auth/JWT/PostgREST reais locais e núcleo descartável.
// Nunca grava JWT, refresh token ou senha na evidência.
import assert from 'node:assert/strict';
import { execFileSync, fork } from 'node:child_process';
import { createHash, randomUUID } from 'node:crypto';
import { once } from 'node:events';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createLabCore } from '../laboratorio-marco-2b/nucleo.mjs';
import { createAuthorization, initializeAuthorization } from '../laboratorio-marco-2b/autorizacao.mjs';
import { restoreDisposable } from '../laboratorio-marco-2b/backup.mjs';

const root=resolve(import.meta.dirname,'../..');
const docker=resolve(process.env.ProgramFiles,'Docker/Docker/resources/bin/docker.exe');
const allowed=resolve(root,'backups/marco-2e-ensaios');
const directory=resolve(allowed,'auth-'+randomUUID()),anchorPath=directory+'.anchor.json',authorizationPath=directory+'.authorization.json';
const backupDir=resolve(allowed,'backup-'+randomUUID()),restoreDir=resolve(allowed,'restore-'+randomUUID()),restoreAnchor=restoreDir+'.anchor.json';
const resultPath=new URL('./resultado-2e.json',import.meta.url),planPath=new URL('./plano-testes-2e.json',import.meta.url);
const sha=b=>createHash('sha256').update(b).digest('hex');
const cases=[];const test=(name,run)=>cases.push({name,run});
const body=()=>({contract_version:1,idempotency_key:randomUUID()});
const report={at:new Date().toISOString(),scope:'Exclusivamente local e sintético — SIMULAÇÃO SEM VALOR OFICIAL',checks:[],passed:false};
let worker,accounts,adminAccessToken,j1,j2,j3,m1,race,jEvent,mEvent,oldBody,mariaBody;
let createPreviewAccounts,revokePreviewAccount,base,anon,serviceKey;

function wait(child,predicate){return new Promise((ok,fail)=>{const timer=setTimeout(()=>{clean();fail(Error('IPC_TIMEOUT'));},45000);function clean(){clearTimeout(timer);child.off('message',receive);child.off('exit',end);}function receive(v){if(predicate(v)){clean();ok(v);}}function end(){clean();fail(Error('PROCESSO_ENCERROU'));}child.on('message',receive);child.on('exit',end);});}
async function start(){const child=fork(resolve(root,'04_BANCO_E_SUPABASE/laboratorio-marco-2d/processo-ensaio.mjs'),[],{stdio:['ignore','ignore','ignore','ipc'],windowsHide:true});const ready=wait(child,v=>v.ready||v.error);child.send({command:'init',directory,anchorPath,authorizationPath,anonKey:anon,serviceKey});const v=await ready;assert.equal(v.ready,true);worker={child,port:v.port};}
async function command(command,extra={}){const id=randomUUID(),pending=wait(worker.child,v=>v.id===id);worker.child.send({id,command,...extra});const result=await pending;if(result.error)throw Error(result.error);return result;}
async function stop(){if(!worker)return;const exit=once(worker.child,'exit');await command('shutdown');await exit;worker=null;}
async function request(token,path='/lab-point/v1/events',payload){const response=await fetch(`http://127.0.0.1:${worker.port}${path}`,{method:payload===undefined?'GET':'POST',headers:{Origin:'http://127.0.0.1:3101',Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:typeof payload==='object'?JSON.stringify(payload):undefined,signal:AbortSignal.timeout(15000)});return {status:response.status,data:await response.json()};}
async function login(account){const r=await fetch(base+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:anon,'Content-Type':'application/json'},body:JSON.stringify({email:account.email,password:account.password}),signal:AbortSignal.timeout(10000)});return {status:r.status,data:await r.json()};}
async function refresh(session){const r=await fetch(base+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:anon,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token}),signal:AbortSignal.timeout(10000)});return r.status;}
async function count(){return (await command('snapshot')).snapshot.events.length;}
const token=s=>s.data.access_token;
const claim=s=>JSON.parse(Buffer.from(token(s).split('.')[1],'base64url').toString());

test('Base 2D imutável confere por SHA-256',async()=>{const actual=sha(readFileSync(resolve(root,'outputs/Metallo-Marco2D-BaselineAprovada-20260927-R1.zip')));assert.equal(actual,'15d5e791c3237f8c7c98d316ddef7220c256ddc8b5b011f9c289741ab1691dd3');report.origin_sha256=actual;});
test('Contas e sessões sintéticas locais preparadas',async()=>{({createPreviewAccounts,revokePreviewAccount,base,anon}=await import('../laboratorio-marco-1a/criar-contas-previa-1b.mjs'));const status=JSON.parse(execFileSync(process.execPath,[resolve(root,'node_modules/supabase/dist/supabase.js'),'status','--workdir',resolve(root,'04_BANCO_E_SUPABASE/laboratorio-marco-1a'),'-o','json'],{encoding:'utf8',env:{...process.env,SUPABASE_TELEMETRY_DISABLED:'1',DO_NOT_TRACK:'1'}}));assert.equal(status.API_URL,base);serviceKey=status.SERVICE_ROLE_KEY;({accounts,adminAccessToken}=await createPreviewAccounts());[j1,j2,m1,race]=await Promise.all([login(accounts.joao),login(accounts.joao),login(accounts.maria),login(accounts.expira)]);for(const s of [j1,j2,m1,race])assert.equal(s.status,200);assert.notEqual(claim(j1).session_id,claim(j2).session_id);mkdirSync(allowed,{recursive:true});const core=await createLabCore(directory,{mode:'create',anchorPath});for(const kind of ['joao','maria','expira'])await core.seedSynthetic({authUserId:accounts[kind].id,employeeId:accounts[kind].employeeId,workerRef:'LAB-'+kind.toUpperCase(),employmentRef:'LAB-VINCULO-'+kind.toUpperCase()});const id=(await core.db.query('select database_id from lab_recovery_state')).rows[0].database_id;await core.close();initializeAuthorization(authorizationPath,id);const prepared=await createLabCore(directory,{anchorPath,authorizationPath});for(const kind of ['joao','maria','expira'])await prepared.registerAuthorization(accounts[kind].id,accounts[kind].employeeId);await prepared.close();await start();});
test('JWT real assinado e duas sessões independentes de João',async()=>{assert.equal(JSON.parse(Buffer.from(token(j1).split('.')[0],'base64url')).alg,'ES256');assert.notEqual(claim(j1).session_id,claim(j2).session_id);assert.equal((await request(token(j1))).status,200);assert.equal((await request(token(j2))).status,200);});
test('Duas abas com a mesma sessão de João consultam somente João',async()=>{const views=await Promise.all([request(token(j1)),request(token(j1))]);assert.ok(views.every(r=>r.status===200&&Array.isArray(r.data.events)));});
test('João confirma intenção K uma única vez',async()=>{oldBody=body();jEvent=await request(token(j1),undefined,oldBody);assert.equal(jEvent.status,201);assert.equal(await count(),1);});
test('Maria confirma evento próprio',async()=>{mariaBody=body();mEvent=await request(token(m1),undefined,mariaBody);assert.equal(mEvent.status,201);assert.equal(await count(),2);});
test('ID de funcionário fornecido pelo cliente é recusado',async()=>{const r=await request(token(j1),undefined,{...body(),employee_id:accounts.maria.employeeId});assert.equal(r.status,400);assert.equal(await count(),2);});
test('João e Maria não leem intenção um do outro',async()=>{assert.equal((await request(token(j1),'/lab-point/v1/intent/'+mariaBody.idempotency_key)).status,404);assert.equal((await request(token(m1),'/lab-point/v1/intent/'+oldBody.idempotency_key)).status,404);});
test('RPC interna de sessão recusa JWT do portal',async()=>{const response=await fetch(base+'/rest/v1/rpc/lab_active_session_2e',{method:'POST',headers:{apikey:anon,Authorization:`Bearer ${token(j1)}`,'Content-Type':'application/json'},body:JSON.stringify({p_session_id:claim(j1).session_id,p_auth_user_id:accounts.joao.id})});assert.ok([401,403,404].includes(response.status));});
test('Admin da Gestão não ganha titularidade nem marca por João',async()=>{const r=await request(adminAccessToken,undefined,body());assert.ok([401,403].includes(r.status));assert.equal(await count(),2);});
test('Funcionário inativo não recebe autorização 2E',async()=>{const inactive=await login(accounts.inativo);assert.equal(inactive.status,200);const r=await request(token(inactive),undefined,body());assert.ok([401,403].includes(r.status));assert.equal(await count(),2);});
test('Backup anterior ao corte conserva apenas os eventos confirmados',async()=>{const b=await command('backup',{directory:backupDir});assert.equal(b.eventCount,2);});
test('Auth indisponível nega nova marcação sem usar snapshot permissivo',async()=>{execFileSync(docker,['pause','supabase_auth_laboratorio-marco-1a'],{stdio:'ignore'});try{const r=await request(token(j1),undefined,body());assert.equal(r.status,503);assert.equal(await count(),2);}finally{execFileSync(docker,['unpause','supabase_auth_laboratorio-marco-1a'],{stdio:'ignore'});}});
test('SAIR encerra somente a sessão atual no núcleo e no Auth',async()=>{const r=await request(token(j1),'/lab-point/v1/session/current','');assert.equal(r.status,200);assert.equal(r.data.scope,'local');});
test('JWT antigo da sessão encerrada não marca nem lê histórico',async()=>{assert.ok([401,403].includes((await request(token(j1),undefined,body())).status));assert.ok([401,403].includes((await request(token(j1))).status));assert.equal(await count(),2);});
test('A segunda aba da mesma sessão encerrada também é negada',async()=>{const staleTabToken=token(j1);assert.ok([401,403].includes((await request(staleTabToken,undefined,body())).status));assert.equal(await count(),2);});
test('Segunda sessão de João continua após SAIR local',async()=>{assert.equal((await request(token(j2),undefined,body())).status,201);assert.equal(await count(),3);});
test('Versão alterada durante a transação desfaz intenção da sessão ainda ativa',async()=>{const other=await login(accounts.joao);assert.equal(other.status,200);const before=await count();await command('set_failpoint',{phase:'after_insert'});const hookWait=wait(worker.child,v=>v.hook==='after_insert');const inFlight=request(token(j2),undefined,body());await hookWait;const snapshot=(await command('authorization_snapshot')).snapshot;createAuthorization(authorizationPath,snapshot.database_id).logoutCurrent(accounts.joao.id,claim(other).session_id);await command('release');const result=await inFlight;assert.equal(result.status,409);assert.equal(result.data.error,'AUTORIZACAO_DESATUALIZADA');assert.equal(await count(),before);assert.equal((await request(token(j2))).status,200);});
test('Refresh da sessão local encerrada falha',async()=>assert.ok((await refresh(j1))>=400));
test('SAIR DE TODOS encerra a segunda sessão e retorna escopo global',async()=>{const r=await request(token(j2),'/lab-point/v1/session/global','');assert.equal(r.status,200);assert.equal(r.data.scope,'global');assert.equal((await command('authorization_snapshot')).snapshot.people[accounts.joao.id].global_logout_pending,false);});
test('Todas as sessões anteriores ao corte global são negadas',async()=>{for(const s of [j1,j2])assert.ok([401,403].includes((await request(token(s),undefined,body())).status));assert.equal(await count(),3);});
test('Refresh da segunda sessão após logout global falha',async()=>assert.ok((await refresh(j2))>=400));
test('Nova sessão após logout global volta somente se vínculo segue ativo',async()=>{await new Promise(ok=>setTimeout(ok,1200));j3=await login(accounts.joao);assert.equal(j3.status,200);assert.equal((await request(token(j3))).status,200);});
test('Retry de K já confirmado recupera o mesmo original antes da revogação',async()=>{const r=await request(token(j3),undefined,oldBody);assert.equal(r.status,200);assert.deepEqual(r.data.event,jEvent.data.event);assert.equal(await count(),3);});
test('Revogação pessoal avança authorization_version e bloqueia o núcleo',async()=>{const before=(await command('authorization_snapshot')).snapshot.people[accounts.joao.id].authorization_version;await revokePreviewAccount(accounts.joao.identityId,adminAccessToken);const applied=await command('authorization_state',{authUserId:accounts.joao.id,state:'REVOKED'});assert.equal(applied.version,before+1);assert.equal((await command('authorization_snapshot')).snapshot.people[accounts.joao.id].state,'REVOKED');});
test('Token residual criptograficamente válido não cria evento',async()=>{assert.ok(claim(j3).exp>Math.floor(Date.now()/1000));assert.ok([401,403].includes((await request(token(j3),undefined,body())).status));assert.equal(await count(),3);});
test('Retry de K revogada preserva original sem nova marcação',async()=>{assert.ok([401,403].includes((await request(token(j3),undefined,oldBody)).status));assert.equal(await count(),3);});
test('Refresh e novo login após revogação falham',async()=>{assert.ok((await refresh(j3))>=400);assert.ok((await login(accounts.joao)).status>=400);});
test('Restart preserva versão e nega token residual',async()=>{await stop();await start();assert.ok([401,403].includes((await request(token(j3),undefined,body())).status));assert.equal((await command('authorization_snapshot')).snapshot.people[accounts.joao.id].state,'REVOKED');assert.equal(await count(),3);});
test('Maria mantém somente seus dados após corte de João',async()=>{const r=await request(token(m1));assert.equal(r.status,200);assert.deepEqual(r.data.events,[mEvent.data.event]);});
test('Falha no logout global mantém corte pendente para token com iat futuro e após restart',async()=>{const before=await count();await command('signout_failure',{enabled:true});const response=await request(token(m1),'/lab-point/v1/session/global','');assert.equal(response.status,503);assert.equal(response.data.error,'ENCERRAMENTO_PENDENTE');await command('signout_failure',{enabled:false});const snapshot=(await command('authorization_snapshot')).snapshot;assert.equal(snapshot.people[accounts.maria.id].global_logout_pending,true);const ledger=createAuthorization(authorizationPath,snapshot.database_id);assert.throws(()=>ledger.authorize({authUserId:accounts.maria.id,employeeId:accounts.maria.employeeId,sessionId:claim(m1).session_id,issuedAt:Math.floor(Date.now()/1000)+30}),e=>e.code==='SESSAO_ENCERRADA');assert.equal((await request(token(m1),undefined,body())).status,401);assert.equal(await count(),before);await stop();await start();assert.equal((await request(token(m1),undefined,body())).status,401);assert.equal(await count(),before);});
test('Revogação na origem entre INSERT e commit faz rollback',async()=>{await command('set_failpoint',{phase:'after_insert'});const before=await count(),raceBody=body();const hookWait=wait(worker.child,v=>v.hook==='after_insert');const inFlight=request(token(race),undefined,raceBody);const hook=await hookWait;assert.equal(hook.hook,'after_insert');await revokePreviewAccount(accounts.expira.identityId,adminAccessToken);await command('release');const r=await inFlight;assert.ok([401,403].includes(r.status));await command('authorization_state',{authUserId:accounts.expira.id,state:'REVOKED'});assert.ok([401,403].includes((await request(token(race),undefined,raceBody)).status));assert.equal(await count(),before);});
test('Restore antigo com âncora atual entra em RECOVERY_REQUIRED',async()=>{await stop();await restoreDisposable(backupDir,restoreDir,{anchorPath:restoreAnchor,referenceAnchor:anchorPath});const restored=await createLabCore(restoreDir,{anchorPath:restoreAnchor,authorizationPath});assert.equal((await restored.inspect()).state,'RECOVERY_REQUIRED');assert.equal(restored.authorizationSnapshot().people[accounts.joao.id].state,'REVOKED');await assert.rejects(restored.record(accounts.joao.id,body(),{employeeId:accounts.joao.employeeId,session:{sessionId:claim(j3).session_id,issuedAt:claim(j3).iat}}),e=>e.code==='RECUPERACAO_NECESSARIA');await restored.close();});
test('Contexto STALE e UNKNOWN falha fechado para Maria',async()=>{const core=await createLabCore(directory,{anchorPath,authorizationPath});await core.applyAuthorizationState(accounts.maria.id,'STALE');const session={sessionId:claim(m1).session_id,issuedAt:claim(m1).iat};await assert.rejects(core.record(accounts.maria.id,body(),{employeeId:accounts.maria.employeeId,session}),e=>e.code==='AUTORIZACAO_NAO_COMPROVADA');await core.applyAuthorizationState(accounts.maria.id,'UNKNOWN');await assert.rejects(core.record(accounts.maria.id,body(),{employeeId:accounts.maria.employeeId,session}),e=>e.code==='AUTORIZACAO_NAO_COMPROVADA');await core.close();});

const names=cases.map(c=>c.name);
if(process.argv.includes('--plan')){writeFileSync(planPath,JSON.stringify({declared_at:new Date().toISOString(),expected:names.length,cases:names},null,2)+'\n');console.log(JSON.stringify({declared:names.length,tests_executed:0,sha256:sha(readFileSync(planPath))}));process.exit(0);}
const plan=JSON.parse(readFileSync(planPath,'utf8'));assert.equal(plan.expected,names.length);assert.deepEqual(plan.cases,names);report.plan_sha256=sha(readFileSync(planPath));report.expected=names.length;
try{for(const c of cases){try{await c.run();report.checks.push({name:c.name,ok:true});console.log('PASS '+c.name);}catch(error){report.checks.push({name:c.name,ok:false,error:error.code??error.message?.slice(0,120)??'ERRO'});throw error;}}report.passed=true;}catch(error){report.error=error.code??error.message?.slice(0,120)??'ERRO';process.exitCode=1;}
finally{if(worker){try{await stop();}catch{worker?.child.kill('SIGKILL');}}if(report.passed){for(const path of [directory,anchorPath,authorizationPath,backupDir,restoreDir,restoreAnchor])if(existsSync(path)){assert.ok(path.startsWith(allowed+'\\'));rmSync(path,{recursive:true,force:true});}report.disposable_environment_removed=true;}if(existsSync(resultPath)){const prior=JSON.parse(readFileSync(resultPath,'utf8'));report.previous_runs=[...(prior.previous_runs??[]),{at:prior.at,passed:prior.passed,checks:prior.checks,error:prior.error??null}];}writeFileSync(resultPath,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:report.passed,checks:report.checks.length,expected:report.expected,error:report.error??null}));}
