import * as laboratoryTransport from "@/05_ACESSO_A_DADOS/Ponto/transporte-laboratorio";
import { pointLaboratoryFetch } from "@/05_ACESSO_A_DADOS/Ponto/transporte-laboratorio";
// @vitest-environment node
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { NextRequest } from "next/server";
import { GET, POST } from "@/app/api/ponto-registros/[...path]/route";
import { buildPointReceipt } from "@/03_FUNCOES_E_LOGICA/Relatorios/ponto-recibo-4b";
vi.mock("@/03_FUNCOES_E_LOGICA/Relatorios/ponto-recibo-4b", async original => ({ ...await original<typeof import("@/03_FUNCOES_E_LOGICA/Relatorios/ponto-recibo-4b")>(), buildPointReceipt: vi.fn(async () => new Uint8Array([37,80,68,70])) }));
const event = { event_id: "00000000-0000-4000-8000-000000000001", reference: "LAB-4A-1", marking_at: "2026-10-01T12:00:00.000Z", recorded_at: "2026-10-01T12:00:08.000Z", timezone: "America/Fortaleza", source: "4A", historical_data: "LIMITED" };
const token = "synthetic.test.token-value", fetcher = vi.fn<typeof fetch>();
const context = (path: string) => ({ params: Promise.resolve({ path: path.split("/") }) });
const request = (path: string, method = "GET", body?: object, host = "127.0.0.1:3101") => new NextRequest(`http://${host}/api/ponto-registros/${path}`, { method, headers: { Host: host, Authorization: `Bearer ${token}`, Origin: `http://${host}`, "Content-Type": "application/json" }, ...(body ? { body: JSON.stringify(body) } : {}) });
beforeEach(() => { vi.spyOn(laboratoryTransport, "pointLaboratoryFetch").mockImplementation((url, options) => fetch(url, options)); vi.stubEnv("METALLO_LOCAL_PREVIEW", "1"); vi.stubEnv("METALLO_COLABORADOR_PREVIEW", "1"); fetcher.mockReset(); fetcher.mockImplementation(async url => Response.json(String(url).endsWith("authorize") ? { authorized: true } : event)); vi.stubGlobal("fetch", fetcher); vi.mocked(buildPointReceipt).mockResolvedValue(new Uint8Array([37,80,68,70])); });
afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals(); vi.unstubAllEnvs(); });
it("carga isolada aceita somente a segunda porta loopback prevista", async () => { vi.stubEnv("METALLO_LOAD_TEST_CORE_PORT", "3107"); const path = `receipt/${event.event_id}`; expect((await GET(request(path), context(path))).status).toBe(200); expect(fetcher.mock.calls.every(([url]) => String(url).startsWith("http://127.0.0.1:3107/"))).toBe(true); });
it("configuração de carga não permite host remoto ou porta arbitrária", async () => { for (const value of ["443", "https://remote.invalid", "3106/../../"]) { vi.stubEnv("METALLO_LOAD_TEST_CORE_PORT", value); expect((await GET(request("last48"), context("last48"))).status).toBe(503); } expect(fetcher).not.toHaveBeenCalled(); });
it("PDF revalida autorização depois de gerar e não cria evento", async () => { const path = `receipt/${event.event_id}`; const response = await GET(request(path), context(path)); expect(response.status).toBe(200); expect(fetcher.mock.calls.map(([url]) => String(url))).toEqual([`http://127.0.0.1:3106/lab-point/v4b/${path}`, "http://127.0.0.1:3106/lab-point/v4b/authorize"]); expect(fetcher.mock.calls.every(([, init]) => init?.method === "GET")).toBe(true); expect(response.headers.get("cache-control")).toContain("no-store"); });
it("logout ou revogação durante geração impede a liberação do PDF", async () => { fetcher.mockImplementation(async url => String(url).endsWith("authorize") ? Response.json({ error: "SESSAO_ENCERRADA" }, { status: 401 }) : Response.json(event)); const path = `receipt/${event.event_id}`; const response = await GET(request(path), context(path)); expect(response.status).toBe(401); expect(await response.json()).toEqual({ error: "SESSAO_ENCERRADA" }); expect(response.headers.get("content-type")).not.toContain("pdf"); });
it("revogação após gerar ZIP também bloqueia os bytes", async () => { fetcher.mockImplementation(async url => String(url).endsWith("authorize") ? Response.json({ error: "CONTEXTO_INATIVO" }, { status: 403 }) : Response.json({ events: [event], window: { start: event.marking_at, end: event.recorded_at } })); const response = await GET(request("last48"), context("last48")); expect(response.status).toBe(403); expect(await response.json()).toEqual({ error: "CONTEXTO_INATIVO" }); });
it("falha na dependência de autorização final nunca entrega bytes", async () => { fetcher.mockImplementation(async url => { if (String(url).endsWith("authorize")) throw new Error("network"); return Response.json(event); }); const path = `receipt/${event.event_id}`; expect((await GET(request(path), context(path))).status).toBe(503); });
it("URL, querystring, hostname e método não ampliam a autoridade", async () => { for (const path of ["../secret", "last48?employee_id=other", "receipt/invalid", "authorize"]) expect((await GET(request(path), context(path))).status).toBe(400); expect((await GET(request("last48", "GET", undefined, "192.168.0.3:3101"), context("last48"))).status).toBe(400); expect((await POST(request("last48", "POST", {}), context("last48"))).status).toBe(400); expect(fetcher).not.toHaveBeenCalled(); });
it("gateway desligado fora da prévia não acessa remoto ou laboratório", async () => { vi.stubEnv("METALLO_LOCAL_PREVIEW", "0"); expect((await GET(request("last48"), context("last48"))).status).toBe(404); expect(fetcher).not.toHaveBeenCalled(); });
it("corpo excessivo é interrompido antes do encaminhamento", async () => { expect((await POST(request("list", "POST", { period: "today", extra: "x".repeat(513) }), context("list"))).status).toBe(413); expect(fetcher).not.toHaveBeenCalled(); });
it("refresh com JWT novo continua obrigado a revalidar a mesma sessão", async () => { const path = `receipt/${event.event_id}`, req = request(path); req.headers.set("authorization", "Bearer refreshed.synthetic.test-token"); expect((await GET(req, context(path))).status).toBe(200); expect(fetcher.mock.calls.every(([, init]) => (init?.headers as Record<string,string>).Authorization === "Bearer refreshed.synthetic.test-token")).toBe(true); });

it("transporte vigente sem flag rejeita destino remoto antes de enviar credencial", async () => { vi.mocked(laboratoryTransport.pointLaboratoryFetch).mockRestore(); vi.stubEnv("METALLO_4C_ROUND", ""); for (const url of ["https://remote.invalid/lab-point/v4b/list", "http://192.168.0.3:3107/lab-point/v4b/list", "http://127.0.0.1:443/list", "http://user:pass@127.0.0.1:3107/list", "http://127.0.0.1:3107/list?employee_id=other"]) await expect(pointLaboratoryFetch(url, { headers: { Authorization: "synthetic" } })).rejects.toThrow("ORIGEM_LOCAL_INVALIDA"); expect(fetcher).not.toHaveBeenCalled(); });
it("transporte vigente sem flag mantém aborto e não tenta novamente", async () => { vi.mocked(laboratoryTransport.pointLaboratoryFetch).mockRestore(); vi.stubEnv("METALLO_4C_ROUND", ""); const signal = AbortSignal.abort(); await expect(pointLaboratoryFetch("http://127.0.0.1:3107/lab-point/v4b/list", { signal })).rejects.toThrow(); expect(fetcher).not.toHaveBeenCalled(); });
