// @vitest-environment node
import { expect, it } from "vitest";
import { PDFDocument } from "pdf-lib";
import { unzipSync } from "fflate";
import { buildPointReceipt, buildPointReceiptZip, pointReceiptFilename } from "@/03_FUNCOES_E_LOGICA/Relatorios/ponto-recibo-4b";
import { personalRecord, type PersonalRecord } from "@/05_ACESSO_A_DADOS/Ponto/registros";
const record: PersonalRecord = { event_id: "00000000-0000-4000-8000-000000000001", reference: "LAB-4A-1", marking_at: "2026-10-01T12:00:00.000Z", recorded_at: "2026-10-01T12:00:08.000Z", timezone: "America/Fortaleza", source: "4A", historical_data: "LIMITED" };
it("PDF A4 de uma página e bytes idênticos na regeneração", async () => { const one = await buildPointReceipt(record), two = await buildPointReceipt(record); expect(one).toEqual(two); const pdf = await PDFDocument.load(one); expect(pdf.getPageCount()).toBe(1); expect(pdf.getPage(0).getSize()).toEqual({ width: 595.28, height: 841.89 }); expect(pdf.getCreationDate()?.toISOString()).toBe(record.recorded_at); expect(pdf.getForm().getFields()).toHaveLength(0); });
it("não consulta cadastro atual, rede, relógio ou geolocalização para o conteúdo", async () => { const code = await import("node:fs/promises").then(fs => fs.readFile(new URL("../03_FUNCOES_E_LOGICA/Relatorios/ponto-recibo-4b.ts", import.meta.url), "utf8")); expect(code).not.toMatch(/Date\.now|fetch\(|geolocation|full_name|employee_name|latitude|longitude/); });
it("DTO rejeita latitude, nome retroativo e estado assinado", () => { for (const extra of [{ latitude: -3.7 }, { employee_name: "João" }, { signed: true }]) expect(personalRecord.safeParse({ ...record, ...extra }).success).toBe(false); });
it("rejeita ID e referência com injeção antes de gerar documento", async () => { for (const value of ["../maria", "<script>", "\r\nSet-Cookie:x", ") Tj (" ]) await expect(buildPointReceipt({ ...record, reference: value })).rejects.toThrow(); expect(() => pointReceiptFilename({ ...record, event_id: "../../senha" })).toThrow(); });
it("ZIP reúne exatamente os PDFs associados, sem duplicata ou caminho arbitrário", async () => { const second = { ...record, event_id: "00000000-0000-4000-8000-000000000002", reference: "LAB-4A-2" }; const files = unzipSync(await buildPointReceiptZip([record, second])); expect(Object.keys(files)).toEqual([pointReceiptFilename(record), pointReceiptFilename(second)]); expect(files[pointReceiptFilename(record)]).toEqual(await buildPointReceipt(record)); await expect(buildPointReceiptZip([record, record])).rejects.toThrow("REGISTRO_DUPLICADO"); });
it("não produz pacote vazio ou parcial por excesso", async () => { await expect(buildPointReceiptZip([])).rejects.toThrow(); await expect(buildPointReceiptZip(Array(501).fill(record))).rejects.toThrow(); });
it("legado preserva seus próprios instantes e vínculo exclusivo ao evento", async () => { const legacy = { ...record, source: "LEGACY" as const, reference: `LAB-LEGADO-${record.event_id}`, marking_at: "2026-08-15T03:00:00.000Z", recorded_at: "2026-08-15T03:00:08.000Z" }; const bytes = await buildPointReceipt(legacy); expect(bytes.length).toBeGreaterThan(2000); expect(await buildPointReceipt(legacy)).toEqual(bytes); if (process.env.METALLO_4B_PDF_SAMPLES === "1") { const fs = await import("node:fs/promises"); const logo = new Uint8Array(await fs.readFile(new URL("../public/metallo-logo.png", import.meta.url))); await fs.writeFile(new URL("../../04_BANCO_E_SUPABASE/laboratorio-marco-4b/recibo-legado-sintetico.pdf", import.meta.url), await buildPointReceipt(legacy, logo)); } });
